### ISSUE TITLE
Better support for xdebug call stacks

### ISSUE THREAD

**Issue by jtsternberg** [Rarst/error-log-dashboard-widget#1]
Tried this out today, and it's a cool concept. However, if I have xdebug on, the 10 lines that I get are not enough to even cover one xdebug call stack. I know I can increase the lines, but would be cool to do some regex and somehow have that data collapsible and the 10 'lines' actually be 10 reported issues. Just a thought.

**Comment by Rarst** [comment]
While a possibility, it wasn't quite meant for easy parsing. Personally I use WP backtrace to produce more compact and log–friendly backtrace, see [`backtrace-error-handler.php`](https://gist.github.com/Rarst/3835861).

PS it's nuts to run xdebug in production anyway and widget is mostly for that :)

**Comment by jtsternberg** [comment]
All fair enough. I'll close this and see my way out. ;)
